apiVersion: apps/v1
kind: Deployment
metadata:
  name: project-docker-depl
spec:
  replicas: 2
  selector:
    matchLabels:
      app: project-docker-depl
  template:
    metadata:
      labels:
        app: project-docker-depl
    spec:
      containers:
        - name: project-docker-depl
          image: shivam060200/project-docker:1.0.0
          ports:
            - containerPort: 8080
