apiVersion: apps/v1
kind: Deployment
metadata:
  name: project-docker-depl
spec:
  replicas: 7
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1 #At most 1 pod down during runt ime
      maxSurge: 1     #At most 1 extra pod above desired during update
  selector:
    matchLabels:
      app: project-docker-depl
  template:
    metadata:
      labels:
        app: project-docker-depl
    spec:
      containers:
        - name: project-docker-depl
          image: shivam060200/project-docker:latest
          ports:
            - containerPort: 8080
